version: '3'
services: 
        web:
            build:
                context: .
                dockerfile: Dockerfile.dev
            ports: 
                - "5000:3000"
            volumes:
                - /usr/app/node_modules
                - .\src:/usr/app/src/
                - /usr/app/
        tests:
            build:
                context: .
                dockerfile: Dockerfile.dev
            volumes:
                - /usr/app/node_modules
                - .\src:/usr/app/src/
                - /usr/app/
            command : ["npm","run","test"]
